---
# tasks file for backup_nginx
- name: "check nginx config file exists"
  stat:
    path: '{{ src }}'
  register: nginx_config
  
- debug: 
    var: "{{ nginx_config.stat.exists }}"

- name: "copy nginx config"
  become: yes
  copy:
    src: '{{ src }}'
    dest: '{{ destination }}'
    remote_src: yes
    follow: yes
  when: nginx_config.stat.exists == true
  