---
# tasks file for backup_nginx
- name: "check nginx config file exists"
  stat:
    path: '{{ src }}'
  register: nginx_config

- name: "copy nginx config"
  become: yes
  copy:
    src: '{{ src }}'
    dest: '{{ destination }}'
    remote_src: yes
    follow: yes
  when: nginx_config.stat.exists == true

- name: "check whether if config has been backed up successfully"
  stat:
    path: '{{ destination }}'
  register: nginx_config_bak

- debug: 
    msg: Nginx config file has been backed up successfully
  when: nginx_config_bak.stat.exists == true
  