---
# tasks file for config_nginx
- name: Implement custom port to Nginx
  become: yes
  template:
    src: templates/nginx_port.conf
    dest: "/etc/nginx/nginx.conf"

- name: "Checking whether if nginx is running"
  service_facts:
  register: services_state

- name: "Restart Nginx"
  become: yes
  service:
    name: nginx
    state: restarted
  when: services_state.ansible_facts.services["nginx.service"].state == 'running'

- name: "Checking whether if nginx is running"
  service_facts:
  register: services_state

- debug:
    msg: "Nginx is running successfully"
  when: services_state.ansible_facts.services["nginx.service"].state == 'running'
