---
# tasks file for install_nginx
- name: "Install Nginx"
  become: yes
  package:
    name: nginx
    state: present
  
- name: "Checking whether if nginx is running"
  service_facts:
  register: services_state

- name: "Start Nginx"
  become: yes
  service:
    name: nginx
    state: started
  when: services_state.ansible_facts.services["nginx.service"].state != 'running'

- name: "Check whether if nginx has been started successfully"
  service_facts:
  register: services_state

- debug:
    msg: "Nginx is running successfully"
  when: services_state.ansible_facts.services["nginx.service"].state == 'running'