---
# tasks file for install_nginx
- name: "Install Nginx"
  become: yes
  package:
    name: nginx
    state: present
  notify: 
    - start_nginx

- name: "Start Nginx"
  become: yes
  service:
    name: nginx
    state: started

- name: "check nginx status"
  command: service nginx status
  register: nginx_var

- debug:
    var: '{{nginx_var}}'